- name: update windows 10

  hosts: all

  tasks:

    - name: Update Windows

      ansible.windows.win_updates:

        category_names:

          - SecurityUpdates

          - CriticalUpdates

          - UpdateRollups

        state: installed

        reboot: true

        log_path: C:\ansible.txt
